name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet publish -c Release -o out

    - name: Log in to Docker Hub
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

    - name: Build Docker image
      run: docker build -t juggernauff/devops:latest -f DevOps.API/Dockerfile .

    - name: Push Docker image to Docker Hub
      run: docker push juggernauff/devops:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to server
      run: |
        sshpass -p "${{secrets.SSH_PASSWORD}}" ssh -o StrictHostKeyChecking=no $HOST_USERNAME@$HOST_IP << EOF
        docker pull juggernauff/devops:latest
        docker stop devops || true
        docker rm devops || true
        docker run -d --name devops -p 80:80 juggernauff/devops:latest
        EOF